#!/usr/bin/env bash
# scripts/gates.sh — project-specific quality gates.
#
# Called by the merge gate from inside the worker's rebased worktree. Should
# exit 0 if everything passes, non-zero otherwise. All output (stdout +
# stderr) is captured to .gates.log and attached to the issue if rejected.
#
# This file is owned by the **planner**. The planner writes a real
# implementation as part of its bootstrap mode, after it has decided the
# tech stack in SPEC.md. Until then, this stub is permissive so the first
# builder iterations aren't blocked while planning catches up.
#
# Builders, playtesters, auditors: do not edit this file. If you think
# gates are wrong, file a chore issue or leave a note for the planner.

set -euo pipefail

echo "[gates] no project gates configured yet (planner will populate this on bootstrap)."
echo "[gates] passing trivially."
exit 0
